Vagrant.configure('2') do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  #config.vm.network "NAT", ip: "192.168.137.10", hostname: true
  config.vm.provider "hyperv"
  config.vm.provider :hyperv do |h|
    h.vmname = "vg-bionic64"
    h.maxmemory = 2048
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end
  config.vm.host_name="vg-bio01"          # linux에서 설정될 hostname
  config.vm.synced_folder ".", "/vagrant", disabled: true #Host와 가상머신의 디렉토리 공유 사용안함
  config.vm.provision "shell", path: "./scripts/static.network.sh"
  config.vm.provision "shell", path: "./scripts/client_sshd_setting.sh"
  config.vm.provision "shell", inline: "netplan apply"
end