---
# First install python on all nodes as ansible needs this
- hosts: all
  become: true
  remote_user: vagrant
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""

- name: Install master k3s
  hosts: master
  remote_user: vagrant
  gather_facts: no

  tasks:
     - name: k3s install
       shell: 
         cmd: "curl -sfL https://get.k3s.io | sh -"
       args:
         warn: no

# Retrieve the server token and place it in admin's home (/home/admin)
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  tasks:
    - name: fetch the server token
      fetch:
        src: "/var/lib/rancher/k3s/server/node-token"
        dest: "/home/vagrant/node-token"
        flat: yes
      when: inventory_hostname in groups.master
      #run_once: yes

- hosts: nodes
  remote_user: vagrant
  become: yes
  tasks:
    - set_fact:
        k3s_url: "https://{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}:6443"
        k3s_token: "{{ lookup('file','/home/vagrant/node-token')  }}"
    - name: install k3s on nodes
      shell: "curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -"
      args:
        warn: no
    - debug:
        msg: "curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -"
