Vagrant.configure('2') do |config|
  config.vm.box = "generic/fedora31"
  #config.vm.box_version = "v3.0.30"
  config.vm.provider "hyperv"
  config.vm.provider :hyperv do |h|
    h.vmname = "vg-coreos"
    h.maxmemory = 2048
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end
  config.vm.host_name="vg-coreos"          # linux에서 설정될 hostname
  config.vm.synced_folder ".", "/vagrant", disabled: true #Host와 가상머신의 디렉토리 공유 사용안함
  config.vm.provision "shell", path: "./scripts/static.network.sh"
  config.vm.provision "shell", path: "./scripts/client_sshd_setting.sh"
  config.vm.provision "shell", inline: "sudo systemctl restart systemd-networkd"
  #cfg.vm.network "public_network"     # VirtualBox의 NAT Interface를 선택 IP를 입력하지 않으면 DHCP로 작동
  #cfg.vm.network "forwarded_port", guest:22, host:19201, auto_correct:false, id:"ssh" #Host의 19201 Port로 접속시 가상머신 22Port로 포워딩
  #config.vm.network "NAT", ip: "192.168.137.10", hostname: true
end